### ISSUE TITLE
Is wal_log_hints still not configurable ?

### ISSUE THREAD

**Issue by iomatters** [patroni/patroni#2052]
**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 11.5

Is there still a way to disable use_pg_rewind and setting wal_log_hints = off respectively ?

Thanks.

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/issues/1942

**Comment by iomatters** [comment]
Yes, I looked through that one, I didn't find the explanation on the closure. I agree that not having wal_log_hints/checksums/rewind is a valid use case. I'm currently experiencing a serious performance degradation after switching from the stream replica to Patroni, checked the configs back and forth, the only difference is the wal_log_hints generating tons of WAL iops.

Would you recommend any workaround, what if I disable the rewind and apply a local patch ?

Thanks.

**Comment by CyberDem0n** [comment]
The issue was closed because nobody was planning to work on it.
If you wish to do so - PRs are always welcome.

**Comment by pol-o** [comment]
@iomatters 
resolve it from #3063
