### ISSUE TITLE
Failsafe mode when master doesn't have access to DCS

### ISSUE THREAD

**Issue by fake-genius** [patroni/patroni#3096]
### What happened?

_I am very sorry to create a bug issue but i just don't have access to slack in my country and even vpns seem to not let me in. And i am in a need of an answer. I cannot provide logs as i didn't use this patroni but I examined docs and code and this came to mind_

**Decsription:**
When failsafe_mode is enabled and master fails to update leader, it sends requests to all other nodes and they must accept it in in order for master to continue mastering. Every request is checked to come from an allowed url. In case when
- allowlist parameter is empty
- allowlist_include_members is True

incoming url must be checked to be in a cluster's members, which is maintained in DCS.

**The issue itself:**
If master lost access to DCS in cannot update its' members key in DCS. Therefore the key expires after ttl time passes, request from master is rejected as it comes from a not allowed url, then master demotes.

I know i can fill allowlist parameter with all cluster members and it will solve the problem, but i think it is not intended to do so. Are there any other ways to avoid demotion in such case?

### How can we reproduce it (as minimally and precisely as possible)?

1/ enable failsafe_mode
2/ block all master connections with DCS but remain all master-replica connections
3/ wait ttl seconds

### What did you expect to happen?

master continue to being master as it can connect with replicas via REST

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
None
```

### patronictl show-config

```yaml
None
```

### Patroni log files

```shell
None
```

### PostgreSQL log files

```shell
None
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Again very sorry for creating a bug, i cant seem to find how to remove the label

**Comment by CyberDem0n** [comment]
The issue template is asking so many different questions for a good purpose.
Without having all these little details it is very hard to understand what the problem is.
