### ISSUE TITLE
When patroni executes pg_basebackup, the maxfailures parameter is written as 2. Can this parameter be changed?

### ISSUE THREAD

**Issue by taoasan** [patroni/patroni#3133]
### What happened?

bootstrap.py location as follow: 
def basebackup(self, conn_url: str, env: Dict[str, str], options: Dict[str, Any]) -> Optional[int]:
        # creates a replica data dir using pg_basebackup.
        # this is the default, built-in create_replica_methods
        # tries twice, then returns failure (as 1)
        # uses "stream" as the xlog-method to avoid sync issues
        # supports additional user-supplied options, those are not validated
        maxfailures = 2
        ret = 1
 

Is the parameter maxfailures =2 here fixed? Can it be modified?

### How can we reproduce it (as minimally and precisely as possible)?

When using Pg_basebackup to synchronize data, the network was disconnected twice. The entire program exited without retrying, causing partoni to be reinitialized and the data directory was gone.

### What did you expect to happen?

how can  I modify   the param  maxfailures   i want to modify it to 10 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
# create replica method: default pg_basebackup
  create_replica_methods:
    - basebackup
  basebackup:
    - max-rate: '1000M'
    - checkpoint: fast
    - status-interva: 1s
    - verbose
    - progress
```

### patronictl show-config

```yaml
# create replica method: default pg_basebackup
  create_replica_methods:
    - basebackup
  basebackup:
    - max-rate: '1000M'
    - checkpoint: fast
    - status-interva: 1s
    - verbose
    - progress
```

### Patroni log files

```shell
498311/827826 kB (60%), 0/1 tablespace (...ersistence/data/base/19306/24942)
509544/827826 kB (61%), 0/1 tablespace (...ersistence/data/base/19306/20022)
519880/827826 kB (62%), 0/1 tablespace (...ersistence/data/base/19306/20022)
pg_basebackup: error: could not read COPY data: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
pg_basebackup: removing contents of data directory "/seasql/persistence/data"
Traceback (most recent call last):
  File "/usr/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/__main__.py", line 144, in main
    return patroni_main()
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/__main__.py", line 136, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/daemon.py", line 181, in abstract_main
    controller.run()
File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/__main__.py", line 106, in run
    super(Patroni, self).run()
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/daemon.py", line 126, in run
    self._run_cycle()
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/__main__.py", line 109, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/ha.py", line 1770, in run_cycle
File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/ha.py", line 1770, in run_cycle
    info = self._run_cycle()
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/ha.py", line 1592, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/ha.py", line 1483, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/tos/patroni/lib64/python3.9/site-packages/patroni/ha.py", line 1476, in raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

### PostgreSQL log files

```shell
2024-08-22 14:02:48.645 CST [20103] LOG:  parameter "primary_conninfo" changed to "user=replicator host=172.51.10.195 port=1523 sslmode=prefer application_name=seasql-base-0 gssencmode=prefer channel_binding=prefer target_session_attrs=read-write"
2024-08-22 14:02:48.645 CST [20103] LOG:  parameter "primary_slot_name" changed to "slot1"
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
It's not possible to modify it.
If such expensive  operation failed more than one time it's usually it doesn't make any sense to retry further.

For the future - issues are for bugs. Please use Slack for questions.

**Comment by taoasan** [comment]
OK, thank you very much

**Comment by taoasan** [comment]
However, sometimes the real environment is that the network will jitter. In this case, multiple retries are still necessary. Wouldn't it be better if the user could be provided with a configurable number of maxfailures ?

**Comment by CyberDem0n** [comment]
Since you didn't provide any relevant logs, config files and didn't even specify Patroni version I can't tell help.
I can only guess that you are trying to bootstrap a standby-cluster leader, and it fails.
In this case Patroni exits with the error. It is always safe (and actually also a good practice) to start it back up (or configure Patroni service to do it).

**Comment by taoasan** [comment]
We are creating a backup cluster and synchronizing data from the main cluster. However, during synchronization, due to network problems, the following error was reported: pg_basebackup: error: could not read COPY data: server closed the connection unexpectedly
Checking the source code of patoni, we found that pg_basebackup can only be retried twice. Our remote disaster recovery network speed environment is not very good, so the network is sometimes disconnected, but we still want the pg_basebackup command to be executed normally and successfully after the network becomes better. Comparison Another open source component, stolon, patroni is very good in terms of performance and usage. However, stolon does not seem to have this problem because stolon will retry multiple times until pg_basebackup is executed successfully. Can patroni do this? I personally think this is very important. For a production environment, after all, we cannot guarantee that the network is 100% continuous.

**Comment by CyberDem0n** [comment]
@taoasan have you read my previous message?

**Comment by CyberDem0n** [comment]
What I want to say - Patroni may crash (because of different reasons, not necessarily due to bugs in the code), and the best strategy is to restart it automatically. That will solve your problem.
