### ISSUE TITLE
Slot advance didn't happen on sync standby

### ISSUE THREAD

**Issue by Medzon888** [patroni/patroni#3172]
### What happened?

Cluster with 3 nodes with a synchronous_mode: true. 
When enable static slots, one of the slave start to do a pg_slot_advance as expected but the second one dont do this with error exception in patroni log. 
What the reason it can be?

### How can we reproduce it (as minimally and precisely as possible)?

Its a typical installation but there also about 8 cdc from kafka connectors.

### What did you expect to happen?

Slots advance as usual

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.2
-   PostgreSQL version: 16.4
-   DCS (and its version): 3.5.7

### Patroni configuration file

```yaml
scope: main
namespace: /service/
name: p-pg-server-db-02

log:
  level: DEBUG
  format: '%(asctime)s %(levelname)s: %(message)s'
  max_queue_size: 1000
  dir: /data/pg_data/logs/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: DEBUG
    urllib3: DEBUG

restapi:
  connect_address: p-pg-server-db-02.fqdn:8008
  listen: 0.0.0.0:8008
  authentication:
    username: patroni
    password: ***



etcd3:
  hosts: ***:2379,***:2379,***:2379
  username: root
  password: ***

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    check_timeline: true
    postgresql:
      use_pg_rewind: false
      use_slots: true
      parameters:
        max_connections: 300
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: logical
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
  initdb:
    - encoding: UTF8
    - data-checksums
    - waldir: /data/pg_wal/postgres
  users:
    postgres:
      password: ***
    replica:
      password: ***
      options:
        - replication

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5435
  connect_address: p-pg-server-db-02.fqdn:5435
  data_dir: /data/pg_data/postgres
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /etc/postgresql/16/main
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: ***
    replication:
      username: replica
      password: ***
  create_replica_methods:
    - basebackup
  basebackup:
    waldir: /data/pg_wal/postgres
  parameters:
    unix_socket_directories: /var/run/postgresql
    shared_preload_libraries: pg_stat_statements,auto_explain
    archive_mode: on
    archive_command: wal-g wal-push %p
  pg_hba:
    - local all all trust
    - host all all 127.0.0.1/32 trust
    - host all all 0.0.0.0/0 scram-sha-256
    - host replication replica 127.0.0.1/32 scram-sha-256
    - host replication replica ***/32 scram-sha-256
    - host replication replica ***/32 scram-sha-256
    - host replication replica ***/32 scram-sha-256
  pg_ctl_timeout: 60

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
check_timeline: true
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
pause: true
postgresql:
  parameters:
    max_connections: 1000
    max_locks_per_transaction: 64
    max_logical_replication_workers: 30
    max_prepared_transactions: 0
    max_replication_slots: 30
    max_slot_wal_keep_size: 50000MB
    max_wal_senders: 30
    max_worker_processes: 30
    track_commit_timestamp: false
    wal_level: logical
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  master_data_to_stockreporter_sub:
    database: master_data
    plugin: pgoutput
    type: logical
  tmp_placement_to_reporter_sub:
    database: placement
    plugin: pgoutput
    type: logical
  tmp_storage_to_reporter_sub:
    database: storage
    plugin: pgoutput
    type: logical
  topology_to_reporter_sub:
    database: topology
    plugin: pgoutput
    type: logical
  transaction_log_to_reporter_sub:
    database: transaction_log
    plugin: pgoutput
    type: logical
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
type: logical
```

### Patroni log files

```shell
2024-09-19 16:14:53,721 INFO: Lock owner: p-pg-server-db-03; I am p-pg-server-db-02
2024-09-19 16:14:53,721 DEBUG: does not have lock
2024-09-19 16:14:53,723 DEBUG: Unable to drop unknown replication slot 'transaction_log_rtdwh_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,723 DEBUG: Unable to drop unknown replication slot 'topology_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,724 DEBUG: Unable to drop unknown replication slot 'product_data_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,724 DEBUG: Unable to drop unknown replication slot 'placement_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,724 DEBUG: Unable to drop unknown replication slot 'transaction_log_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,725 DEBUG: Unable to drop unknown replication slot 'storage_rtdwh_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,725 DEBUG: Unable to drop unknown replication slot 'storage_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,725 DEBUG: Unable to drop unknown replication slot 'slotting_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,725 DEBUG: Unable to drop unknown replication slot 'product_data_rtdwh_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,726 DEBUG: Unable to drop unknown replication slot 'placement_rtdwh_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,726 DEBUG: Unable to drop unknown replication slot 'slotting_rtdwh_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,726 DEBUG: Unable to drop unknown replication slot 'topology_rtdwh_pdpkfk_slot', slot is still active
2024-09-19 16:14:53,730 DEBUG: API thread: 10.203.128.11 - - "OPTIONS / HTTP/1.0" 503 - latency: 1.112 ms
2024-09-19 16:14:53,754 ERROR: Exception when changing replication slots
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/patroni/postgresql/slots.py", line 529, in sync_replication_slots
    self.check_logical_slots_readiness(cluster, tags)
  File "/usr/local/lib/python3.10/dist-packages/patroni/postgresql/slots.py", line 589, in check_logical_slots_readiness
    self._ready_logical_slots(catalog_xmin)
  File "/usr/local/lib/python3.10/dist-packages/patroni/postgresql/slots.py", line 640, in _ready_logical_slots
    and primary_logical_catalog_xmin <= primary_physical_catalog_xmin <= standby_logical_catalog_xmin
TypeError: '<=' not supported between instances of 'NoneType' and 'str'
```

### PostgreSQL log files

```shell
nothing special. pg_slot_advance does not exist in log on second slave
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Maybe its because of kfk slots affects somehow. Walsenders on this node cant give me do a switchover or restart a slave until I do a kill walsenders processes for kfk connectors.
With node without kfk all fine.
Of course I can try to test with disable all kfk connectors but maybe there can be explanation of why this error happen?

**Comment by CyberDem0n** [comment]
Why do you have active slots on a standby node?

**Comment by Medzon888** [comment]
We use feature of PostgreSQL16 for creating logical replication slots on replicas. In normal state kafka connectors live on master node and when failover happen then we reinitialize connector to the new master. This process can be long for the large data etc.. As 16 version can handle slots at the slave we dont touch kafka connectors and after failover they automatically create slots on slave (old master). And its work.

**Comment by Medzon888** [comment]
Maybe I need to add every slot as a static here but anywhere no always need to add all of the slots

**Comment by CyberDem0n** [comment]
It seems that you don't really care about missed events when the connector has to reconnect to a different node where there is no replication slots exists...

**Comment by Medzon888** [comment]
I care, previous posts right about this cares and in plans include this slots to the statics. But in this case this is not important because its a testing case and now we include only half slots for another postgres. 
Can this be a reason and I need to include all slots as a static?

**Comment by CyberDem0n** [comment]
In order to not lose any events one must connect only to the primary.

**Comment by Medzon888** [comment]
We are not lose any events with a static slots for kafka. We was testing it in a workload while switchover to the other node. After that connector proceed to work with slot on replica which is safe wal position and on the kafka side no any message lost.

**Comment by Medzon888** [comment]
Anyway post not about data loss :) We trying to handle with error...and to know the reason

**Comment by CyberDem0n** [comment]
Sorry, I am failing to follow you.
The main problem is that you are trying to use some dirty hack that aren't supported.

**Comment by Medzon888** [comment]
Well i try to explain again and clear.

We have patroni cluster with a 3 nodes. 
We implement connector wich is automatically create logical slot and capture data from it.
We configure static logical slots this connector which is used our slots for capture data. When we configure static slots- they automatically created on the slave side and they advance wal position in a cycle right? This mechanism provide us to not loose data on this slots after switchover. 
As wal position on this logical slots is reserved on slave side so we can connect to the slave to capture data from them as from master side. From now - why its wrong? And why when we connected to slave we can loose data?

**Comment by CyberDem0n** [comment]
> As wal position on this logical slots is reserved on slave side so we can connect to the slave to capture data from them as from master side

First of all there are no slaves in a Postgres world. Second, logical slots on standby nodes are "created" only to use them **after** the standby will be promoted to the primary.

**Comment by Medzon888** [comment]
From the PostgreSQL 16 release notes:
`Allow logical replication from standby servers`

**Comment by CyberDem0n** [comment]
Thank, you, I know how to read Postgres docs.
I am telling you about the use-case that Patroni supports.

**Comment by Medzon888** [comment]
That's what I wanted to know. Sad, design of this case is what need HA solution. Sorry for missundestanding.
