### ISSUE TITLE
Patroni should not use ydiff as a module

### ISSUE THREAD

**Issue by ymattw** [patroni/patroni#3218]
### What happened?

[patroni/ctl.py](https://github.com/patroni/patroni/blob/4ce0f99cfb5b08bf770a935c59936a6353e3d27d/patroni/ctl.py#L48) imports [ydiff](https://github.com/ymattw/ydiff) and calls their `markup_to_pager()` with a hacky [opts](https://github.com/patroni/patroni/blob/4ce0f99cfb5b08bf770a935c59936a6353e3d27d/patroni/ctl.py#L1897) to render colored diffs. The author of ydiff was not aware of this and changes they made often breaks patroni users, recent example is the new option `--theme` introduce (see https://github.com/patroni/patroni/issues/3212 and https://github.com/ymattw/ydiff/issues/124). 

Ydiff is intended to be used as a CLI tool, not a python module. Ideally a fix like https://github.com/patroni/patroni/pull/3214 should be applied, once we can make sure the environment Patroni runs always contain an executable `ydiff` or `ydiff.py` in `$PATH`.

### How can we reproduce it (as minimally and precisely as possible)?

See https://github.com/patroni/patroni/issues/3212.

### What did you expect to happen?

Patroni should not break after newer ydiff is released with new CLI options.

### Patroni/PostgreSQL/DCS version

N/a

### Patroni configuration file

```yaml
N/a
```

### patronictl show-config

```yaml
N/a
```

### Patroni log files

```shell
N/a
```

### PostgreSQL log files

```shell
N/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> Ideally a fix like https://github.com/patroni/patroni/pull/3214 should be applied, once we can make sure the environment Patroni runs always contain an executable ydiff or ydiff.py in $PATH

I don't really like the idea of relying on $PATH. From the past experience users have a lot of problems configuring it correctly and I already feel the pain from answering questions about `FileNotFoundError: [Errno 2] No such file or directory: 'ydiff'` exceptions.

Therefore for now I just added `ydiff<1.5` to the requirements.txt and set up an additional pipeline that checks compatibility with new versions of ydiff. I can assure you that in a future you'll get no issues related to Patroni with it. Of course, if you continue bumping major version when there are breaking changes :)

**Comment by CyberDem0n** [comment]
Well, it is slightly better, but as I said, we also need to support cdiff. At this moment it is just easier to handle compatibility by handling ImportError.
In a future we may reconsider it.
